//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyBug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUGS
    {
        public int BugID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string CreatedAt { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public string severity { get; set; }
        public string url { get; set; }
        public string input { get; set; }
        public string Reproduce { get; set; }
        public string Expected { get; set; }
        public string Actual { get; set; }
        public string Env { get; set; }
        public Nullable<int> ProjectMembersID { get; set; }
    }
}
