//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyBug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCTION()
        {
            this.BUGS = new HashSet<BUG>();
            this.PROJECTMBS = new HashSet<PROJECTMB>();
        }
    
        public int FunctionID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string EmailCreater { get; set; }
        public string DateCreated { get; set; }
        public string Description { get; set; }
        public string EmailUser { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUG> BUGS { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTMB> PROJECTMBS { get; set; }
    }
}
