//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyBug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int ID_History { get; set; }
        public Nullable<int> ProjectMembersID { get; set; }
        public string Name_Project { get; set; }
        public string Description_History { get; set; }
        public string Time { get; set; }
        public string Activity { get; set; }
        public Nullable<int> ID_User { get; set; }
    }
}
