//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyBug.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECTS()
        {
            this.PROJECTMBS = new HashSet<PROJECTMBS>();
        }
    
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
        public string DateCreate { get; set; }
        public string PeopleCreate { get; set; }
        public string EmailPeoCreate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTMBS> PROJECTMBS { get; set; }
    }
}
